### ISSUE TITLE
CI  Github Actions deprecations

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU2#1190]
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-python@v4. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

+ [ ] Update CI actions to node js 20
+ [ ] Update actions/upload-artifact and actions/download-artfact to v4 where required.

**Comment by ptheywood** [comment]
We also need to upgrade use of actions/upload-artifact and actions/download-artifact to v4 by 2024-11-30

> Starting November 30, 2024, GitHub Actions customers will no longer be able to use v3 of [actions/upload-artifact](https://github.com/actions/upload-artifact) or [actions/download-artifact](https://github.com/actions/download-artifact). Customers should update workflows to begin using [v4 of the artifact actions](https://github.blog/2024-02-12-get-started-with-v4-of-github-actions-artifacts/) as soon as possible. While v4 of the artifact actions improves upload and download speeds by up to 98% and includes several new features, there are [key differences](https://github.com/actions/upload-artifact?tab=readme-ov-file#breaking-changes) from previous versions that may require updates to your workflows. Please see [the documentation](https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md) in the project repositories for guidance on how to migrate your workflows.

https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/

**Comment by ptheywood** [comment]
This is blocked by Node 20 actions not being compatible with Centos7 containers due to glibc requirements.

Hopefully this is resolved by github before 2024-11-30... 

See #1200 for the failing implementation of this.

**Comment by ptheywood** [comment]
@Robadob has noticed that the short term workaround to allow Node 16 to be used (`ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION`) appers to have stopped working for the manylinux 2014 (centos7) builds. 

https://github.com/FLAMEGPU/FLAMEGPU2/actions/runs/12036533957/job/33557999089


The actions upload/download_artifact@v3 removal seems to have been pushed back to January 30th 2025, but thankfully we didn't see that before putting 2.0.0-rc.2 out.

**Comment by Robadob** [comment]
> FLAMEGPU/FLAMEGPU2/actions/runs/12036533957/job/33557999089

This will expire soon so:

```
Run actions/checkout@v3
  with:
    repository: FLAMEGPU/FLAMEGPU[2](https://github.com/FLAMEGPU/FLAMEGPU2/actions/runs/12036533957/job/33557999089#step:3:2)
    token: ***
    ssh-strict: true
    persist-credentials: true
    clean: true
    sparse-checkout-cone-mode: true
    fetch-depth: 1
    fetch-tags: false
    lfs: false
    submodules: false
    set-safe-directory: true
  env:
    AUDITWHEEL_REPAIR: OFF
    MANYLINUX: manylinux2014
    ARCH: x86_64
    USE_STATIC_GLEW: ON
    ARTIFACT_NAME: wheel-manylinux2014-12.0-[3](https://github.com/FLAMEGPU/FLAMEGPU2/actions/runs/12036533957/job/33557999089#step:3:3).12-OFF-Release-ubuntu-20.04
    BUILD_DIR: build
    FLAMEGPU_BUILD_TESTS: OFF
    FLAMEGPU_BUILD_PYTHON: ON
    CUDA: 12.0
    CUDA_ARCH: 50
    HOSTCXX: devtoolset-10
    OS: ubuntu-20.0[4](https://github.com/FLAMEGPU/FLAMEGPU2/actions/runs/12036533957/job/33557999089#step:3:4)
    CONFIG: Release
    FLAMEGPU_SEATBELTS: ON
    PYTHON: 3.12
    VISUALISATION: OFF
    ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
/usr/bin/docker exec  a3ddb818d3f9a48ad[5](https://github.com/FLAMEGPU/FLAMEGPU2/actions/runs/12036533957/job/33557999089#step:3:5)2d4e553a7cde145892ae85[6](https://github.com/FLAMEGPU/FLAMEGPU2/actions/runs/12036533957/job/33557999089#step:3:6)6760604771a97834a851cb0 sh -c "cat /etc/*release | grep ^ID"
/__e/node20/bin/node: /lib64/libm.so.6: version `GLIBC_2.2[7](https://github.com/FLAMEGPU/FLAMEGPU2/actions/runs/12036533957/job/33557999089#step:3:7)' not found (required by /__e/node20/bin/node)
/__e/node20/bin/node: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /__e/node20/bin/node)
/__e/node20/bin/node: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /__e/node20/bin/node)
/__e/node20/bin/node: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /__e/node20/bin/node)
/__e/node20/bin/node: /lib64/libc.so.6: version `GLIBC_2.2[8](https://github.com/FLAMEGPU/FLAMEGPU2/actions/runs/12036533957/job/33557999089#step:3:8)' not found (required by /__e/node20/bin/node)
/__e/node20/bin/node: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /__e/node20/bin/node)
```
